### ISSUE TITLE
spell source update

### ISSUE THREAD

**Issue by Yrrcoon** [theShmoo/DSA5SpellBook#5]
Hey there,

realy great to see your work. 
But while I'm typing this message, Ulisses has updatet their webside with lots of new spells. Could you set loose your spiders to get all the new spells and update your DSA5SpellBook?
That would be awesom :)

**Comment by theShmoo** [comment]
Thank you for your notification! I will let you know when the new spells are updated.

**Comment by theShmoo** [comment]
I added the new spells. There are still some errors but currently there are over 660 spells in my database. Which is nice :)

**Comment by Yrrcoon** [comment]
great! Thanks :)

**Comment by MeisterOek** [comment]
There are lots of new spells from "Aventutrische Magie 2"
