### ISSUE TITLE
Spells and dropdowns not displayed correctly

### ISSUE THREAD

**Issue by Excelsior90** [theShmoo/DSA5SpellBook#6]
Don't know why, but Spells and dropdown menus are not displayed correctly

![spellbook_bug](https://user-images.githubusercontent.com/38854187/39421852-41151372-4c6b-11e8-8c66-40c573c3dfe3.JPG)

**Comment by theShmoo** [comment]
Hi! Thanks for the Ticket! I will fix it :)

**Comment by theShmoo** [comment]
Fixed it in the most recent commit.
