### ISSUE TITLE
Wrong Bootstrap Version

### ISSUE THREAD

**Issue by supermopf** [theShmoo/DSA5SpellBook#9]
In your telease you are using the latest version of Bootstrap but your app is written in 3.3.7

To fix this change
`https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css`
to
`https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css`

**Comment by theShmoo** [comment]
Thank you very much for your input! 
I restructured the spell book and it will be updated in a few weeks! 
Stay tuned for the repo https://github.com/theShmoo/DSA5WebTools which is a parent for more DSA5 tools. The spell book will be a part of this.
